databases:
  - name: risdb
    plan: free
    databaseName: ris
    user: ris

services:
  - type: web
    plan: free
    name: ris
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ris.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: risdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4